environment:
  matrix:
    - node_version: "8"
    - node_version: "7"
    - node_version: "6"
    - node_version: "4"

install:
  - ps: Install-Product node $env:node_version
  - npm install

build_script:
  - npm run build

test_script:
  - node --version
  - npm run test
